
```{r packages}
library(here)
library(tidyverse)
library(sf)
library(patchwork)
library(gt)
library(glue)
library(showtext)
library(tidycensus)
library(ggh4x)
library(lemon)
library(tigris)
library(here)

options(scipen = 9999)
set.seed(708)
dir.create(here('figures'), showWarnings = FALSE)
```

```{r theme}
# Set Font Arial
showtext_auto()
font_add("Arial", regular = here("assets/LiberationSans-Regular.ttf"))
base_size = 16
theme_set(
  ggplot2::theme_minimal(
    base_family = 'Arial',
    base_size = base_size
  ) +
    ggplot2::theme(
      legend.background = element_blank(),
      legend.key = element_blank(),
      panel.background = element_blank(),
      panel.border = element_blank(),
      strip.background = element_blank(),
      plot.background = element_blank(),
      axis.line = element_blank(),
      panel.grid = element_blank(),
      plot.title = element_text(size = base_size + 14L),
      plot.subtitle = element_text(size = base_size + 8L),
      #panel.border = element_rect(color = "grey25", fill = NA, size = .25),
      #plot.title = element_text(size = 18),
      axis.text.x = element_text(angle = 90, vjust = +.5),
      axis.ticks = element_line(),
      panel.spacing = unit(0, 'in')
      #axis.title.y = element_blank()
    )
)
```

```{r data}
#| echo: false
#| message: false
if (!file.exists(here('data/raw/wfbz_disasters_2000-2025.geojson'))) {
  stop(
    "Manually download data set from https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DWILBW and unzip to data/raw."
  )
}

source(here::here('R/utils.R'))

wfbz <- read_sf(here("data/raw/wfbz_disasters_2000-2025.geojson")) %>%
  filter(!st_is_empty(geometry)) %>%
  filter(wildfire_year < 2025)
wfbz <- wfbz %>%
  filter(!str_detect(wildfire_complex_names, '(FLOOD$|FLOOD 2013$)')) # remove some colorado floods that snuck in

states_sf <- tigris::states(progress_bar = FALSE)

if (!file.exists(here('data/raw/tiger_counties.geojson'))) {
  counties_pop <- get_decennial(
    geography = "county",
    variables = "P1_001N", # Total population variable in 2020 Census
    year = 2020,
    geometry = TRUE,
    output = "wide",
    progress_bar = FALSE
  ) %>%
    rename(population = P1_001N) %>%
    select(population, geometry)
  write_sf(counties_pop, here('data/raw/tiger_counties.geojson'))
} else {
  counties_pop <- here('data/raw/tiger_counties.geojson')
}

if (!file.exists(here('data/raw/tiger_states.geojson'))) {
  states_pop <- get_decennial(
    geography = "state",
    variables = "P1_001N", # Total population variable in 2020 Census
    year = 2020,
    geometry = TRUE,
    output = "wide",
    progress_bar = FALSE
  ) %>%
    rename(population = P1_001N) %>%
    select(NAME, population, geometry) %>%
    left_join(
      tidycensus::fips_codes %>%
        select(state_abb = state, NAME = state_name) %>%
        distinct()
    ) %>%
    rename(state_name = NAME)
  write_sf(states_pop, here('data/raw/tiger_states.geojson'))
} else {
  states_pop <- read_sf(here('data/raw/tiger_states.geojson'))
}

# Order regions consistently
REGION_ORDER <- tibble(
  usfs_region = c(
    "California",
    "Southern",
    "Alaska",
    "Southern Rockies",
    "Southwestern",
    "Northern Rockies",
    "Intermountain",
    "Pacific Northwest",
    "Eastern",
    "Hawaii"
  ),
  plot_order = 10:1
)
# Palette
region_colors <- c(khroma::color('light', reverse = FALSE)(9), '#ac87cc')
region_colors[region_colors == '#dddddd'] <- '#757575' # lil darker
attr(region_colors, "missing") <- NA
names(region_colors) <- sort(REGION_ORDER$usfs_region)


if (!file.exists(here('data/processed/regions.geojson'))) {
  regions <- read_sf(unzip_url(
    "https://data.fs.usda.gov/geodata/edw/edw_resources/shp/S_USA.AdministrativeRegion.zip",
    dst = tempfile(fileext = ".shp")
  )) %>%
    select(usfs_region = REGIONNAME) %>%
    mutate(usfs_region = str_replace(usfs_region, " Region", ""))

  regions <- bind_rows(
    regions,
    st_filter(
      regions %>%
        filter(usfs_region == 'Pacific Southwest') %>%
        st_cast("POLYGON"),
      states_sf %>% filter(STUSPS == 'HI')
    ) %>%
      group_by(usfs_region) %>%
      summarize(geometry = st_combine(geometry)) %>%
      mutate(usfs_region = 'Hawaii'),
    st_filter(
      regions %>%
        filter(usfs_region == 'Pacific Southwest') %>%
        st_cast("POLYGON"),
      states_sf %>% filter(STUSPS == 'CA')
    ) %>%
      group_by(usfs_region) %>%
      summarize(geometry = st_combine(geometry)) %>%
      mutate(usfs_region = 'California')
  ) %>%
    filter(usfs_region != 'Pacific Southwest') %>%
    mutate(
      usfs_region = if_else(
        usfs_region == 'Northern',
        'Northern Rockies',
        usfs_region
      )
    ) %>%
    mutate(
      usfs_region = if_else(
        usfs_region == 'Rocky Mountain',
        'Southern Rockies',
        usfs_region
      )
    )

  regions$usfs_region_pop <- aggregate(
    st_centroid(counties_pop),
    regions,
    FUN = sum
  )$population # centroid more or less ensures counties only end up in one region

  write_sf(regions, here('data/processed/regions.geojson'))
} else {
  regions <- read_sf(here('data/processed/regions.geojson'))
}
```

```{r plotme_fn}
# Plot Main Figures Showing Variables over Time
plotme <- function(
  dat,
  var,
  rel = FALSE,
  unit = NA,
  stack = TRUE,
  line = FALSE
) {
  # Determine order to plot in
  region_summary <- dat %>%
    ungroup() %>%
    group_by(usfs_region) %>%
    summarize(tot = sum(get(var), na.rm = TRUE), .groups = 'drop') %>%
    mutate(pcttot = tot / sum(tot)) %>%
    inner_join(REGION_ORDER, by = 'usfs_region') %>%
    arrange(plot_order)

  region_order <- as.character(region_summary$usfs_region)

  # Add details to labels
  if (!stack) {
    region_label <- region_summary$usfs_region
  } else if (rel) {
    region_label <- paste0(
      as.character(region_summary$usfs_region),
      ' (',
      format(100 * region_summary$pcttot, digits = 1),
      '%)'
    )
  } else {
    region_label <- paste0(
      as.character(region_summary$usfs_region),
      ' (',
      str_replace(
        format(round(region_summary$tot), big.mark = ','),
        '\\s+',
        ''
      ),
      ')'
    )
  }

  # Reassign colors to regions now that they have been updated
  names(region_colors) <- sort(region_label)

  dat$usfs_region <- factor(
    dat$usfs_region,
    levels = region_order,
    labels = region_label
  )

  # Summarize and Plot
  if (!stack) {
    dat %>%
      ggplot() +
      geom_col(
        aes(x = wildfire_year, y = get(var), fill = usfs_region),
        color = "grey25",
        linewidth = .1,
        width = 1
      ) +
      scale_fill_manual(
        values = region_colors,
        guide = 'none'
      ) +
      facet_wrap(
        facets = ~ fct_rev(usfs_region),
        ncol = 2,
        drop = TRUE,
        scales = 'free'
      ) +
      scale_x_continuous(
        expand = expansion(mult = c(0, 0)),
        limits = c(1999.5, 2024.5),
        breaks = seq(2000, 2024, by = 2),
        minor_breaks = 1999.5:2024.5
      ) +
      scale_y_continuous(
        expand = expansion(mult = c(0, 0)),
        limits = c(0, 100),
        labels = ~ paste0(.x, '%')
      ) +
      xlab(NULL) +
      ylab(glue("{var}{if_else(is.na(unit), '', paste0(' (', unit, ')'))}")) +
      theme(
        panel.border = element_rect(color = "grey25", fill = NA, size = .25),
        plot.title = element_text(size = 14),
        axis.text.x = element_text(angle = 90, vjust = +.5),
        axis.ticks = element_line(),
        plot.margin = unit(c(0, 0, 0, 0), "pt"),
        panel.grid.minor.x = element_line(color = "grey25", size = .1),
        panel.background = element_rect(fill = "white")
      )
  } else if (rel) {
    dat %>%
      ggplot() +
      geom_col(
        aes(x = wildfire_year, y = get(var), fill = usfs_region),
        color = "grey25",
        linewidth = .1,
        width = 1,
        position = position_fill()
      ) +
      scale_fill_manual(
        name = "Region (Overall Share)",
        values = region_colors
      ) +
      scale_x_continuous(
        expand = expansion(mult = c(0, 0)),
        limits = c(1999.5, 2024.5),
        breaks = seq(2000, 2024, by = 2)
      ) +
      scale_y_continuous(
        expand = expansion(mult = c(0, 0)),
        labels = scales::percent
      ) +
      xlab(NULL) +
      ylab(glue("{var} (Share of Total)")) +
      theme(
        panel.border = element_rect(color = "grey25", fill = NA, size = .25),
        plot.title = element_text(size = 14),
        axis.text.x = element_text(angle = 90, vjust = +.5),
        axis.ticks = element_line(),
        plot.margin = unit(c(0, 0, 0, 0), "pt"),
        axis.title.x = element_blank()
      )
  } else if (line) {
    dat %>%
      ggplot() +
      geom_line(
        aes(x = wildfire_year, y = get(var), color = usfs_region),
      ) +
      geom_point(
        aes(x = wildfire_year, y = get(var), color = usfs_region),
      ) +
      scale_color_manual(
        name = "Region (Overall Share)",
        values = region_colors
      ) +
      scale_x_continuous(
        expand = expansion(mult = c(0, 0)),
        limits = c(1999.5, 2024.5),
        breaks = seq(2000, 2024, by = 2)
      ) +
      scale_y_continuous(
        expand = expansion(mult = c(0, 0)),
        labels = scales::percent
      ) +
      xlab(NULL) +
      ylab(glue("{var} (Share of Total)")) +
      theme(
        panel.border = element_rect(color = "grey25", fill = NA, size = .25),
        plot.title = element_text(size = 14),
        axis.text.x = element_text(angle = 90, vjust = +.5),
        axis.ticks = element_line(),
        plot.margin = unit(c(0, 0, 0, 0), "pt")
      )
  } else {
    dat %>%
      ggplot() +
      geom_col(
        aes(x = wildfire_year, y = get(var), fill = usfs_region),
        color = "grey25",
        linewidth = .1,
        width = 1
      ) +
      scale_fill_manual(
        name = "Region (Overall Total)",
        values = region_colors
      ) +
      scale_x_continuous(
        expand = expansion(mult = c(0, 0)),
        limits = c(1999.5, 2024.5),
        breaks = seq(2000, 2024, by = 2)
      ) +
      scale_y_continuous(
        expand = expansion(mult = c(0, 0)),
        labels = scales::label_comma()
      ) +
      xlab(NULL) +
      ylab(glue("{var}{if_else(is.na(unit), '', paste0(' (', unit, ')'))}")) +
      theme(
        panel.border = element_rect(color = "grey25", fill = NA, size = .25),
        plot.title = element_text(size = 14),
        axis.text.x = element_text(angle = 90, vjust = +.5),
        axis.ticks = element_line(),
        plot.margin = unit(c(0, 0, 0, 0), "pt"),
        axis.title.x = element_blank()
      )
  }
}
```

```{r}
# Find Nearest Region
wfbz_region <- regions$usfs_region[st_nearest_feature(
  wfbz,
  regions,
  pairwise = TRUE
)]
wfbz_region_area <- as.numeric(
  st_area(regions)[st_nearest_feature(wfbz, regions, pairwise = TRUE)] /
    1000 /
    1000
)
wfbz_region_pop <- regions$usfs_region_pop[st_nearest_feature(
  wfbz,
  regions,
  pairwise = TRUE
)]

by_state <- wfbz %>%
  st_drop_geometry() %>%
  mutate(
    state_abb = str_split(wildfire_states, '\\|')
  ) %>%
  unnest(state_abb) %>%
  left_join(st_drop_geometry(states_pop)) %>%
  left_join(
    st_centroid(states_sf, of_largest_polygon = TRUE) %>%
      st_join(regions) %>%
      st_drop_geometry() %>%
      select(STUSPS, usfs_region),
    by = join_by(state_abb == STUSPS)
  ) %>%
  filter(wildfire_community_intersect) %>%
  group_by(usfs_region, state_abb, state_name) %>%
  summarize(
    `Events` = n(),
    `Fatalities` = sum(wildfire_max_civil_fatalities, na.rm = TRUE),
    `Fatalities per 100K` = 100000 *
      sum(wildfire_max_civil_fatalities / population, na.rm = TRUE),
    `Structures Destroyed` = sum(wildfire_struct_destroyed, na.rm = TRUE),
    `FEMA Declarations` = sum(wildfire_fema_dec, na.rm = TRUE),
    `FEMA Declaration Percent` = `FEMA Declarations` / `Events`,
    `Burned Area` = sum(wildfire_area, na.rm = TRUE),
    `WUI` = sum(
      str_detect(wildfire_wui, '(intermix|interface)'),
      na.rm = TRUE
    ),
    .groups = 'drop'
  )
by_state <- by_state %>%
  arrange(desc(`FEMA Declaration Percent`), state_abb) %>%
  mutate(
    state_abb = factor(row_number(), levels = row_number(), labels = state_abb),
    state_name = factor(
      row_number(),
      levels = row_number(),
      labels = state_name
    )
  )


wfbz_crit <- wfbz %>%
  st_drop_geometry() %>%
  mutate(
    usfs_region = wfbz_region,
    usfs_region_area = wfbz_region_area,
    usfs_region_pop = wfbz_region_pop
  ) %>%
  filter(wildfire_community_intersect) %>%
  group_by(usfs_region, wildfire_year) %>%
  summarize(
    `Events` = n(),
    `Fatalities` = sum(wildfire_max_civil_fatalities, na.rm = TRUE),
    `Fatalities per 100K` = 100000 *
      sum(wildfire_max_civil_fatalities / usfs_region_pop, na.rm = TRUE),
    `Structures Destroyed` = sum(wildfire_struct_destroyed, na.rm = TRUE),
    `FEMA Declarations (n)` = sum(wildfire_fema_dec, na.rm = TRUE),
    `Burned Area` = sum(wildfire_area, na.rm = TRUE),
    `Burned Area Percent` = 100 *
      sum(wildfire_area / usfs_region_area, na.rm = TRUE),
    `WUI` = sum(str_detect(wildfire_wui, '(intermix|interface)'), na.rm = TRUE),
    `WUI Percent` = 100 *
      sum(str_detect(wildfire_wui, '(interface|intermix)'), na.rm = TRUE) /
      n(),
    `Mean Fire Size` = mean(wildfire_area, na.rm = TRUE),
    .groups = 'drop'
  )
```
