---
title: "Population Exposure over Time"
toc: true
execute:
  echo: false
  warning: false
  message: false
---
{{< include _setup.qmd >}}
{{< include _pop_setup.qmd >}}


```{r}
hexgrid <- st_make_grid(states_pop, square = FALSE, n = c(500, 500)) %>%
  st_as_sf() %>%
  mutate(hexid = row_number()) %>%
  st_filter(states_pop)


wfbz_hex <- hexgrid %>%
  st_join(
    wfbz %>%
      mutate(
        usfs_region = wfbz_region,
        usfs_region_area = wfbz_region_area,
        usfs_region_pop = wfbz_region_pop
      ) %>%
      inner_join(
        read_csv(here('data/processed/pop_affected_per_fire.csv')),
        by = c(wildfire_id = "ID_hazard")
      ),
    left = FALSE
  ) %>%
  filter(wildfire_community_intersect) %>%
  group_by(hexid, geometry = x) %>%
  summarize(
    `Median pop.\n exposed` = median(`exposed_10km`, na.rm = TRUE),
    .groups = 'drop'
  )

wfbz_by_region <- wfbz %>%
  mutate(
    usfs_region = wfbz_region,
    usfs_region_area = wfbz_region_area,
    usfs_region_pop = wfbz_region_pop
  ) %>%
  st_drop_geometry() %>%
  inner_join(
    read_csv(here('data/processed/pop_affected_per_fire.csv')),
    by = c(wildfire_id = "ID_hazard")
  ) %>%
  filter(wildfire_community_intersect) %>%
  group_by(usfs_region, wildfire_year) %>%
  summarize(
    `Median pop. exposed` = median(exposed_10km, na.rm = TRUE),
    .groups = 'drop'
  ) %>%
  left_join(REGION_ORDER, by = "usfs_region")


mapme <- function(
  dat,
  var,
  flab = \(.x) scales::comma(.x, accuracy = 1),
  unit = NULL,
  breaks,
  logscale = TRUE
) {
  if (logscale == TRUE) {
    values <- scales::rescale(scales::pseudo_log_trans()$transform(breaks))
  } else {
    values <- scales::rescale(breaks)
  }

  ggplot() +
    geom_sf(
      data = shift_geometry(dat),
      aes(fill = get(var)),
      color = NA
    ) +
    geom_sf(data = shift_geometry(states_pop), fill = NA, color = 'grey25') +
    scale_fill_stepsn(
      colors = grey.colors(5, start = 0.95, end = 0.15),
      name = str_wrap(
        if_else(is.null(unit), var, paste0(var, '(', unit, ')')),
        width = 12
      ),
      labels = flab,
      n.breaks = 5,
      breaks = breaks,
      values = values,
      transform = if_else(
        logscale == TRUE,
        'pseudo_log',
        'identity'
      )
    ) +
    coord_sf(expand = FALSE) +
    theme(
      axis.ticks.x = element_blank(),
      axis.ticks.y = element_blank(),
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.line = element_blank(),
      plot.margin = margin(0, 0, 0, 0),
      legend.margin = margin(0, 0, 0, l = 75),
      #legend.position = 'bottom',
      legend.position = "left",
      legend.justification = "top",
      legend.text = element_text(hjust = 0, vjust = -.5),
      panel.spacing = unit(0, "lines")
    )
}
```

```{r pop_over_time, fig.height = 12, fig.width = 8}
pop <- read_csv(here('data/processed/pop_affected.csv')) %>%
  rename(
    wildfire_year = year,
    `Population Affected` = exposed_10km,
    usfs_region = region
  ) %>%
  select(-ID_hazard)

pop_labels <- pop %>%
  left_join(REGION_ORDER) %>%
  mutate(
    tot = sum(
      `Population Affected`,
      na.rm = TRUE
    )
  ) %>%
  group_by(usfs_region, plot_order, tot) %>%
  reframe(
    label_abs = paste0(
      usfs_region,
      ' (',
      scales::comma(
        mean(
          `Population Affected`,
          na.rm = TRUE
        )
      ),
      ')'
    ),
    label_rel = paste0(
      usfs_region,
      ' (',
      scales::percent(
        sum(
          `Population Affected`,
          na.rm = TRUE
        ) /
          tot,
        accuracy = .1
      ),
      ')'
    )
  ) %>%
  distinct() %>%
  mutate(label_abs = fct_reorder(label_abs, plot_order)) %>%
  mutate(label_rel = fct_reorder(label_rel, plot_order))

pop <- pop %>% left_join(pop_labels)

names(region_colors) <- sort(as.character(pop_labels$label_abs))

p_abs <- ggplot(data = pop) +
  geom_col(
    aes(
      x = wildfire_year,
      y = `Population Affected`,
      fill = label_abs
    ),
    width = 1,
    linewidth = 0.25,
    color = 'grey25'
  ) +
  scale_fill_manual(
    name = "Region (Overall Annual Mean)",
    values = region_colors
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, by = 2),
    expand = expansion(add = c(0, 0))
  ) +
  #    coord_cartesian(xlim = c(2000, 2025)) +
  scale_y_continuous(
    labels = scales::comma,
    expand = expansion(mult = c(0, 0))
  ) +
  xlab(NULL) +
  ylab('Population Affected') +
  pop_theme +
  theme(
    legend.position = 'right' #,
  )

names(region_colors) <- sort(as.character(pop_labels$label_rel))

p_rel <- ggplot(data = pop) +
  geom_col(
    aes(
      x = wildfire_year,
      y = `Population Affected`,
      fill = label_rel
    ),
    width = 1,
    linewidth = 0.25,
    color = 'grey25',
    position = position_fill()
  ) +
  scale_fill_manual(name = "Region (Overall Share)", values = region_colors) +
  scale_x_continuous(
    breaks = seq(2000, 2024, by = 2),
    expand = expansion(add = c(0, 0))
  ) +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0)),
    labels = scales::percent
  ) +
  xlab(NULL) +
  ylab(glue("Population Affected (Share of Total)")) +
  pop_theme +
  theme(
    legend.position = 'right' #,
  )

p <- p_abs +
  plot_spacer() +
  p_rel +
  plot_layout(ncol = 1, heights = c(5, 1, 5), widths = c(3, 3, 3))
p
ggsave(here('figures/pop_over_time.pdf'), last_plot(), width = 8, height = 8)
```

### Median by fire

```{r pop_by_fire_over_time, fig.height = 12, fig.width = 8}
p <- plotme(dat = wfbz_by_region, 'Median pop. exposed') +
  plot_spacer() +
  plotme(dat = wfbz_by_region, 'Median pop. exposed', rel = TRUE) +
  plot_spacer() +
  free(
    mapme(
      wfbz_hex,
      'Median pop.\n exposed',
      breaks = c(
        0,
        scales::breaks_log(n = 6, base = 10)(c(
          1,
          max(wfbz_hex$`Median pop.\n exposed`, na.rm = TRUE)
        ))
      )
    ),
    type = 'panel'
  ) +
  plot_layout(ncol = 1, heights = c(5, 1, 5, .5, 6), widths = c(3, 3, 3, 3, 4))
p
ggsave(
  here('figures/pop_by_fire_over_time.pdf'),
  last_plot(),
  width = 8,
  height = 12
)
```
